import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "chronists",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
        <title>chronists</title>
        <style>{`
          html, body {
            margin: 0;
            height: 100%;
            overflow: hidden;
          }
          iframe {
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            border: 0;
            width: 100%;
            height: 100%;
          }
        `}</style>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Embed YouForm iframe */}
        <iframe
          src="https://app.youform.com/forms/arod7fei"
          loading="lazy"
          title="Chronists Form"
          frameBorder="0"
          marginHeight={0}
          marginWidth={0}
        ></iframe>

        {/* Render page content below the iframe if needed */}
        {children}
      </body>
    </html>
  );
}
